# openssl req -newkey rsa:2048 -nodes -keyout wildcard_key -x509 -days 3650 -out wildcard_certificate
[listen]
ssl = false
cert = "wildcard_certificate"
key = "wildcard_key"
port = 8080

[chrome]
host = "localhost"
port = 9222
